#ifndef _COMMON_CONSTANTS_H_
#define _COMMON_CONSTANTS_H_

#define FIRMWARE_VERSION 1

#define MESSAGE_LENGTH_BYTE_COUNT 1

#define PROTOCOL_ID "CUBO"

#define INTERFACE_MODULE_ADDRESS  0

//function ids
typedef enum FunctionId{
//FID_GET_PARAMETERS = 0,
FID_GET_PROTOCOL_ID = 1,
//FID_GET_NEIGHBOR_ADDRESS = 2,
FID_GET_STATE = 3,
FID_SET_STATE = 4,
//FID_SET_ADDRESS = 5,
FID_GET_MODE = 6,
FID_SET_MODE = 7,

	FID_COMMAND_FLASH_GET_VERSION = 8,
	FID_COMMAND_FLASH_END = 9,
	FID_COMMAND_FLASH_ADDRESS = 10,
	FID_COMMAND_FLASH_LATCH_WORD = 11,
	FID_COMMAND_FLASH_WRITE_WORD = 12,
	FID_COMMAND_FLASH_CHECKSUM = 13,
	FID_COMMAND_FLASH_SET_BOOT_FLAG = 14,

FID_GET_MODULE_TYPE = 15,
} FunctionId;

typedef enum
{
    TYPE_USB_INTERFACE = 1,
    TYPE_POTENTIOMETER = 2,
    TYPE_RGB_LED = 3,
    TYPE_BUTTON = 4,
    TYPE_ARITHMETIC_LOGIC = 5,
} ModuleTypes;


#endif //_COMMON_CONSTANTS_H_
